const hiddenWords = [{
  "id": "Introduction",
  "exhort": "He Is the Glory of Glories",
  "text": "This is that which hath descended from the realm of glory, uttered by the tongue of power and might, and revealed unto the Prophets of old. We have taken the inner essence thereof and clothed it in the garment of brevity, as a token of grace unto the righteous, that they may stand faithful unto the Covenant of God, may fulfill in their lives His trust, and in the realm of spirit obtain the gem of divine virtue.",
  "teaser": "This is that which hath...",
},
{
  "id": "Arabic01",
  "title": "Arabic 1",
  "section": "Arabic",
  "number": "1",
  "exhort": "O SON OF SPIRIT!",
  "text": "My first counsel is this: Possess a pure, kindly and radiant heart, that thine may be a sovereignty ancient, imperishable and everlasting.",
  "teaser": "My first counsel is this...",
},
{
  "id": "Arabic02",
  "title": "Arabic 2",
  "section": "Arabic",
  "number": "2",
  "exhort": "O SON OF SPIRIT!",
  "text": "The best beloved of all things in My sight is Justice; turn not away therefrom if thou desirest Me, and neglect it not that I may confide in thee. By its aid thou shalt see with thine own eyes and not through the eyes of others, and shalt know of thine own knowledge and not through the knowledge of thy neighbor. Ponder this in thy heart; how it behooveth thee to be. Verily justice is My gift to thee and the sign of My loving-kindness. Set it then before thine eyes.",
  "teaser": "The best beloved of all things...",
},
{
  "id": "Arabic03",
  "title": "Arabic 3",
  "section": "Arabic",
  "number": "3",
  "exhort": "O SON OF MAN!",
  "text": "Veiled in My immemorial being and in the ancient eternity of My essence, I knew My love for thee; therefore I created thee, have engraved on thee Mine image and revealed to thee My beauty.",
  "teaser": "Veiled in My immemorial being...",
},
{
  "id": "Arabic04",
  "title": "Arabic 4",
  "section": "Arabic",
  "number": "4",
  "exhort": "O SON OF MAN!",
  "text": "I loved thy creation, hence I created thee. Wherefore, do thou love Me, that I may name thy name and fill thy soul with the spirit of life.",
  "teaser": "I loved thy creation...",
},
{
  "id": "Arabic05",
  "title": "Arabic 5",
  "section": "Arabic",
  "number": "5",
  "exhort": "O SON OF BEING!",
  "text": "Love Me, that I may love thee. If thou lovest Me not, My love can in no wise reach thee. Know this, O servant.",
  "teaser": "Love Me, that I may...",
},
{
  "id": "Arabic06",
  "title": "Arabic 6",
  "section": "Arabic",
  "number": "6",
  "exhort": "O SON OF BEING!",
  "text": "Thy Paradise is My love; thy heavenly home, reunion with Me. Enter therein and tarry not. This is that which hath been destined for thee in Our kingdom above and Our exalted dominion.",
  "teaser": "Thy Paradise is My love...",
},
{
  "id": "Arabic07",
  "title": "Arabic 7",
  "section": "Arabic",
  "number": "7",
  "exhort": "O SON OF MAN!",
  "text": "If thou lovest Me, turn away from thyself; and if thou seekest My pleasure, regard not thine own; that thou mayest die in Me and I may eternally live in thee.",
  "teaser": "If thou lovest Me...",
},
{
  "id": "Arabic08",
  "title": "Arabic 8",
  "section": "Arabic",
  "number": "8",
  "exhort": "O SON OF SPIRIT!",
  "text": "There is no peace for thee save by renouncing thyself and turning unto Me; for it behooveth thee to glory in My name, not in thine own; to put thy trust in Me and not in thyself, since I desire to be loved alone and above all that is.",
  "teaser": "There is no peace for...",
},
{
  "id": "Arabic09",
  "title": "Arabic 9",
  "section": "Arabic",
  "number": "9",
  "exhort": "O SON OF BEING!",
  "text": "My love is My stronghold; he that entereth therein is safe and secure, and he that turneth away shall surely stray and perish.",
  "teaser": "My love is My stronghold...",
},
{
  "id": "Arabic10",
  "title": "Arabic 10",
  "section": "Arabic",
  "number": "10",
  "exhort": "O SON OF UTTERANCE!",
  "text": "Thou art My stronghold; enter therein that thou mayest abide in safety. My love is in thee, know it, that thou mayest find Me near unto thee.",
  "teaser": "Thou art My stronghold...",
},
{
  "id": "Arabic11",
  "title": "Arabic 11",
  "section": "Arabic",
  "number": "11",
  "exhort": "O SON OF BEING!",
  "text": "Thou art My lamp and My light is in thee. Get thou from it thy radiance and seek none other than Me. For I have created thee rich and have bountifully shed My favor upon thee.",
  "teaser": "Thou art My lamp...",
},
{
  "id": "Arabic12",
  "title": "Arabic 12",
  "section": "Arabic",
  "number": "12",
  "exhort": "O SON OF BEING!",
  "text": "With the hands of power I made thee and with the fingers of strength I created thee; and within thee have I placed the essence of My light. Be thou content with it and seek naught else, for My work is perfect and My command is binding. Question it not, nor have a doubt thereof.",
  "teaser": "With the hands of power...",
},
{
  "id": "Arabic13",
  "title": "Arabic 13",
  "section": "Arabic",
  "number": "13",
  "exhort": "O SON OF SPIRIT!",
  "text": "I created thee rich, why dost thou bring thyself down to poverty? Noble I made thee, wherewith dost thou abase thyself? Out of the essence of knowledge I gave thee being, why seekest thou enlightenment from anyone beside Me? Out of the clay of love I molded thee, how dost thou busy thyself with another? Turn thy sight unto thyself, that thou mayest find Me standing within thee, mighty, powerful and self-subsisting.",
  "teaser": "I created thee rich...",
},
{
  "id": "Arabic14",
  "title": "Arabic 14",
  "section": "Arabic",
  "number": "14",
  "exhort": "O SON OF MAN!",
  "text": "Thou art My dominion and My dominion perisheth not; wherefore fearest thou thy perishing? Thou art My light and My light shall never be extinguished; why dost thou dread extinction? Thou art My glory and My glory fadeth not; thou art My robe and My robe shall never be outworn. Abide then in thy love for Me, that thou mayest find Me in the realm of glory.",
  "teaser": "Thou art My dominion...",
},
{
  "id": "Arabic15",
  "title": "Arabic 15",
  "section": "Arabic",
  "number": "15",
  "exhort": "O SON OF UTTERANCE!",
  "text": "Turn thy face unto Mine and renounce all save Me; for My sovereignty endureth and My dominion perisheth not. If thou seekest another than Me, yea, if thou searchest the universe forevermore, thy quest will be in vain.",
  "teaser": "Turn thy face unto Mine...",
},
{
  "id": "Arabic16",
  "title": "Arabic 16",
  "section": "Arabic",
  "number": "16",
  "exhort": "O SON OF LIGHT!",
  "text": "Forget all save Me and commune with My spirit. This is of the essence of My command, therefore turn unto it.",
  "teaser": "Forget all save Me...",
},
{
  "id": "Arabic17",
  "title": "Arabic 17",
  "section": "Arabic",
  "number": "17",
  "exhort": "O SON OF MAN!",
  "text": "Be thou content with Me and seek no other helper. For none but Me can ever suffice thee.",
  "teaser": "Be thou content with Me...",
},
{
  "id": "Arabic18",
  "title": "Arabic 18",
  "section": "Arabic",
  "number": "18",
  "exhort": "O SON OF SPIRIT!",
  "text": "Ask not of Me that which We desire not for thee, then be content with what We have ordained for thy sake, for this is that which profiteth thee, if therewith thou dost content thyself.",
  "teaser": "Ask not of Me...",
},
{
  "id": "Arabic19",
  "title": "Arabic 19",
  "section": "Arabic",
  "number": "19",
  "exhort": "O SON OF THE WONDROUS VISION!",
  "text": "I have breathed within thee a breath of My own Spirit, that thou mayest be My lover. Why hast thou forsaken Me and sought a beloved other than Me?",
  "teaser": "I have breathed...",
},
{
  "id": "Arabic20",
  "title": "Arabic 20",
  "section": "Arabic",
  "number": "20",
  "exhort": "O SON OF SPIRIT!",
  "text": "My claim on thee is great, it cannot be forgotten. My grace to thee is plenteous, it cannot be veiled. My love has made in thee its home, it cannot be concealed. My light is manifest to thee, it cannot be obscured.",
  "teaser": "My claim on thee is great...",
},
{
  "id": "Arabic21",
  "title": "Arabic 21",
  "section": "Arabic",
  "number": "21",
  "exhort": "O SON OF MAN!",
  "text": "Upon the tree of effulgent glory I have hung for thee the choicest fruits, wherefore hast thou turned away and contented thyself with that which is less good? Return then unto that which is better for thee in the realm on high.",
  "teaser": "Upon the tree of effulgent glory...",
},
{
  "id": "Arabic22",
  "title": "Arabic 22",
  "section": "Arabic",
  "number": "22",
  "exhort": "O SON OF SPIRIT!",
  "text": "Noble have I created thee, yet thou hast abased thyself. Rise then unto that for which thou wast created.",
  "teaser": "Noble have I created thee...",
},
{
  "id": "Arabic23",
  "title": "Arabic 23",
  "section": "Arabic",
  "number": "23",
  "exhort": "O SON OF THE SUPREME!",
  "text": "To the eternal I call thee, yet thou dost seek that which perisheth. What hath made thee turn away from Our desire and seek thine own?",
  "teaser": "To the eternal I call thee...",
},
{
  "id": "Arabic24",
  "title": "Arabic 24",
  "section": "Arabic",
  "number": "24",
  "exhort": "O SON OF MAN!",
  "text": "Transgress not thy limits, nor claim that which beseemeth thee not. Prostrate thyself before the countenance of thy God, the Lord of might and power.",
  "teaser": "Transgress not thy limits...",
},
{
  "id": "Arabic25",
  "title": "Arabic 25",
  "section": "Arabic",
  "number": "25",
  "exhort": "O SON OF SPIRIT!",
  "text": "Vaunt not thyself over the poor, for I lead him on his way and behold thee in thy evil plight and confound thee forevermore.",
  "teaser": "Vaunt not thyself over the poor...",
},
{
  "id": "Arabic26",
  "title": "Arabic 26",
  "section": "Arabic",
  "number": "26",
  "exhort": "O SON OF BEING!",
  "text": "How couldst thou forget thine own faults and busy thyself with the faults of others? Whoso doeth this is accursed of Me.",
  "teaser": "How couldst thou forget...",
},
{
  "id": "Arabic27",
  "title": "Arabic 27",
  "section": "Arabic",
  "number": "27",
  "exhort": "O SON OF MAN!",
  "text": "Breathe not the sins of others so long as thou art thyself a sinner. Shouldst thou transgress this command, accursed wouldst thou be, and to this I bear witness.",
  "teaser": "Breathe not the sins of others...",
},
{
  "id": "Arabic28",
  "title": "Arabic 28",
  "section": "Arabic",
  "number": "28",
  "exhort": "O SON OF SPIRIT!",
  "text": "Know thou of a truth: He that biddeth men be just and himself committeth iniquity is not of Me, even though he bear My name.",
  "teaser": "Know thou of a truth...",
},
{
  "id": "Arabic29",
  "title": "Arabic 29",
  "section": "Arabic",
  "number": "29",
  "exhort": "O SON OF BEING!",
  "text": "Ascribe not to any soul that which thou wouldst not have ascribed to thee, and say not that which thou doest not. This is My command unto thee, do thou observe it.",
  "teaser": "Ascribe not to any soul...",
},
{
  "id": "Arabic30",
  "title": "Arabic 30",
  "section": "Arabic",
  "number": "30",
  "exhort": "O SON OF MAN!",
  "text": "Deny not My servant should he ask anything from thee, for his face is My face; be then abashed before Me.",
  "teaser": "Deny not My servant...",
},
{
  "id": "Arabic31",
  "title": "Arabic 31",
  "section": "Arabic",
  "number": "31",
  "exhort": "O SON OF BEING!",
  "text": "Bring thyself to account each day ere thou art summoned to a reckoning; for death, unheralded, shall come upon thee and thou shalt be called to give account for thy deeds.",
  "teaser": "Bring thyself to account...",
},
{
  "id": "Arabic32",
  "title": "Arabic 32",
  "section": "Arabic",
  "number": "32",
  "exhort": "O SON OF THE SUPREME!",
  "text": "I have made death a messenger of joy to thee. Wherefore dost thou grieve? I made the light to shed on thee its splendor. Why dost thou veil thyself therefrom?",
  "teaser": "I have made death...",
},
{
  "id": "Arabic33",
  "title": "Arabic 33",
  "section": "Arabic",
  "number": "33",
  "exhort": "O SON OF SPIRIT!",
  "text": "With the joyful tidings of light I hail thee: rejoice! To the court of holiness I summon thee; abide therein that thou mayest live in peace forevermore.",
  "teaser": "With the joyful tidings...",
},
{
  "id": "Arabic34",
  "title": "Arabic 34",
  "section": "Arabic",
  "number": "34",
  "exhort": "O SON OF SPIRIT!",
  "text": "The spirit of holiness beareth unto thee the joyful tidings of reunion; wherefore dost thou grieve? The spirit of power confirmeth thee in His cause; why dost thou veil thyself? The light of His countenance doth lead thee; how canst thou go astray?",
  "teaser": "The spirit of holiness...",
},
{
  "id": "Arabic35",
  "title": "Arabic 35",
  "section": "Arabic",
  "number": "35",
  "exhort": "O SON OF MAN!",
  "text": "Sorrow not save that thou art far from Us. Rejoice not save that thou art drawing near and returning unto Us.",
  "teaser": "Sorrow not save that thou art far...",
},
{
  "id": "Arabic36",
  "title": "Arabic 36",
  "section": "Arabic",
  "number": "36",
  "exhort": "O SON OF MAN!",
  "text": "Rejoice in the gladness of thine heart, that thou mayest be worthy to meet Me and to mirror forth My beauty.",
  "teaser": "Rejoice in the gladness...",
},
{
  "id": "Arabic37",
  "title": "Arabic 37",
  "section": "Arabic",
  "number": "37",
  "exhort": "O SON OF MAN!",
  "text": "Divest not thyself of My beauteous robe, and forfeit not thy portion from My wondrous fountain, lest thou shouldst thirst forevermore.",
  "teaser": "Divest not thyself...",
},
{
  "id": "Arabic38",
  "title": "Arabic 38",
  "section": "Arabic",
  "number": "38",
  "exhort": "O SON OF BEING!",
  "text": "Walk in My statutes for love of Me and deny thyself that which thou desirest if thou seekest My pleasure.",
  "teaser": "Walk in My statutes...",
},
{
  "id": "Arabic39",
  "title": "Arabic 39",
  "section": "Arabic",
  "number": "39",
  "exhort": "O SON OF MAN!",
  "text": "Neglect not My commandments if thou lovest My beauty, and forget not My counsels if thou wouldst attain My good pleasure.",
  "teaser": "Neglect not My commandments...",
},
{
  "id": "Arabic40",
  "title": "Arabic 40",
  "section": "Arabic",
  "number": "40",
  "exhort": "O SON OF MAN!",
  "text": "Wert thou to speed through the immensity of space and traverse the expanse of heaven, yet thou wouldst find no rest save in submission to Our command and humbleness before Our Face.",
  "teaser": "Wert thou to speed through...",
},
{
  "id": "Arabic41",
  "title": "Arabic 41",
  "section": "Arabic",
  "number": "41",
  "exhort": "O SON OF MAN!",
  "text": "Magnify My cause that I may reveal unto thee the mysteries of My greatness and shine upon thee with the light of eternity.",
  "teaser": "Magnify My cause...",
},
{
  "id": "Arabic42",
  "title": "Arabic 42",
  "section": "Arabic",
  "number": "42",
  "exhort": "O SON OF MAN!",
  "text": "Humble thyself before Me, that I may graciously visit thee. Arise for the triumph of My cause, that while yet on earth thou mayest obtain the victory.",
  "teaser": "Humble thyself before Me...",
},
{
  "id": "Arabic43",
  "title": "Arabic 43",
  "section": "Arabic",
  "number": "43",
  "exhort": "O SON OF BEING!",
  "text": "Make mention of Me on My earth, that in My heaven I may remember thee, thus shall Mine eyes and thine be solaced.",
  "teaser": "Make mention of Me...",
},
{
  "id": "Arabic44",
  "title": "Arabic 44",
  "section": "Arabic",
  "number": "44",
  "exhort": "O SON OF THE THRONE!",
  "text": "Thy hearing is My hearing, hear thou therewith. Thy sight is My sight, do thou see therewith, that in thine inmost soul thou mayest testify unto My exalted sanctity, and I within Myself may bear witness unto an exalted station for thee.",
  "teaser": "Thy hearing is My hearing...",
},
{
  "id": "Arabic45",
  "title": "Arabic 45",
  "section": "Arabic",
  "number": "45",
  "exhort": "O SON OF BEING!",
  "text": "Seek a martyr’s death in My path, content with My pleasure and thankful for that which I ordain, that thou mayest repose with Me beneath the canopy of majesty behind the tabernacle of glory.",
  "teaser": "Seek a martyr’s death...",
},
{
  "id": "Arabic46",
  "title": "Arabic 46",
  "section": "Arabic",
  "number": "46",
  "exhort": "O SON OF MAN!",
  "text": "Ponder and reflect. Is it thy wish to die upon thy bed, or to shed thy lifeblood on the dust, a martyr in My path, and so become the manifestation of My command and the revealer of My light in the highest paradise? Judge thou aright, O servant!",
  "teaser": "Ponder and reflect...",
},
{
  "id": "Arabic47",
  "title": "Arabic 47",
  "section": "Arabic",
  "number": "47",
  "exhort": "O SON OF MAN!",
  "text": "By My beauty! To tinge thy hair with thy blood is greater in My sight than the creation of the universe and the light of both worlds. Strive then to attain this, O servant!",
  "teaser": "By My beauty! To tinge thy hair...",
},
{
  "id": "Arabic48",
  "title": "Arabic 48",
  "section": "Arabic",
  "number": "48",
  "exhort": "O SON OF MAN!",
  "text": "For everything there is a sign. The sign of love is fortitude under My decree and patience under My trials.",
  "teaser": "For everything there is a sign...",
},
{
  "id": "Arabic49",
  "title": "Arabic 49",
  "section": "Arabic",
  "number": "49",
  "exhort": "O SON OF MAN!",
  "text": "The true lover yearneth for tribulation even as doth the rebel for forgiveness and the sinful for mercy.",
  "teaser": "The true lover yearneth...",
},
{
  "id": "Arabic50",
  "title": "Arabic 50",
  "section": "Arabic",
  "number": "50",
  "exhort": "O SON OF MAN!",
  "text": "If adversity befall thee not in My path, how canst thou walk in the ways of them that are content with My pleasure? If trials afflict thee not in thy longing to meet Me, how wilt thou attain the light in thy love for My beauty?",
  "teaser": "If adversity befall thee not...",
},
{
  "id": "Arabic51",
  "title": "Arabic 51",
  "section": "Arabic",
  "number": "51",
  "exhort": "O SON OF MAN!",
  "text": "My calamity is My providence, outwardly it is fire and vengeance, but inwardly it is light and mercy. Hasten thereunto that thou mayest become an eternal light and an immortal spirit. This is My command unto thee, do thou observe it.",
  "teaser": "My calamity is My providence...",
},
{
  "id": "Arabic52",
  "title": "Arabic 52",
  "section": "Arabic",
  "number": "52",
  "exhort": "O SON OF MAN!",
  "text": "Should prosperity befall thee, rejoice not, and should abasement come upon thee, grieve not, for both shall pass away and be no more.",
  "teaser": "Should prosperity befall thee...",
},
{
  "id": "Arabic53",
  "title": "Arabic 53",
  "section": "Arabic",
  "number": "53",
  "exhort": "O SON OF BEING!",
  "text": "If poverty overtake thee, be not sad; for in time the Lord of wealth shall visit thee. Fear not abasement, for glory shall one day rest on thee.",
  "teaser": "If poverty overtake thee...",
},
{
  "id": "Arabic54",
  "title": "Arabic 54",
  "section": "Arabic",
  "number": "54",
  "exhort": "O SON OF BEING!",
  "text": "If thine heart be set upon this eternal, imperishable dominion, and this ancient, everlasting life, forsake this mortal and fleeting sovereignty.",
  "teaser": "If thine heart be set...",
},
{
  "id": "Arabic55",
  "title": "Arabic 55",
  "section": "Arabic",
  "number": "55",
  "exhort": "O SON OF BEING!",
  "text": "Busy not thyself with this world, for with fire We test the gold, and with gold We test Our servants.",
  "teaser": "Busy not thyself...",
},
{
  "id": "Arabic56",
  "title": "Arabic 56",
  "section": "Arabic",
  "number": "56",
  "exhort": "O SON OF MAN!",
  "text": "Thou dost wish for gold and I desire thy freedom from it. Thou thinkest thyself rich in its possession, and I recognize thy wealth in thy sanctity therefrom. By My life! This is My knowledge, and that is thy fancy; how can My way accord with thine?",
  "teaser": "Thou dost wish for gold...",
},
{
  "id": "Arabic57",
  "title": "Arabic 57",
  "section": "Arabic",
  "number": "57",
  "exhort": "O SON OF MAN!",
  "text": "Bestow My wealth upon My poor, that in heaven thou mayest draw from stores of unfading splendor and treasures of imperishable glory. But by My life! To offer up thy soul is a more glorious thing couldst thou but see with Mine eye.",
  "teaser": "Bestow My wealth upon My poor...",
},
{
  "id": "Arabic58",
  "title": "Arabic 58",
  "section": "Arabic",
  "number": "58",
  "exhort": "O SON OF MAN!",
  "text": "The temple of being is My throne; cleanse it of all things, that there I may be established and there I may abide.",
  "teaser": "The temple of being is My throne...",
},
{
  "id": "Arabic59",
  "title": "Arabic 59",
  "section": "Arabic",
  "number": "59",
  "exhort": "O SON OF BEING!",
  "text": "Thy heart is My home; sanctify it for My descent. Thy spirit is My place of revelation; cleanse it for My manifestation.",
  "teaser": "Thy heart is My home...",
},
{
  "id": "Arabic60",
  "title": "Arabic 60",
  "section": "Arabic",
  "number": "60",
  "exhort": "O SON OF MAN!",
  "text": "Put thy hand into My bosom, that I may rise above thee, radiant and resplendent.",
  "teaser": "Put thy hand into My bosom...",
},
{
  "id": "Arabic61",
  "title": "Arabic 61",
  "section": "Arabic",
  "number": "61",
  "exhort": "O SON OF MAN!",
  "text": "Ascend unto My heaven, that thou mayest obtain the joy of reunion, and from the chalice of imperishable glory quaff the peerless wine.",
  "teaser": "Ascend unto My heaven...",
},
{
  "id": "Arabic62",
  "title": "Arabic 62",
  "section": "Arabic",
  "number": "62",
  "exhort": "O SON OF MAN!",
  "text": "Many a day hath passed over thee whilst thou hast busied thyself with thy fancies and idle imaginings. How long art thou to slumber on thy bed? Lift up thy head from slumber, for the Sun hath risen to the zenith, haply it may shine upon thee with the light of beauty.",
  "teaser": "Many a day hath passed...",
},
{
  "id": "Arabic63",
  "title": "Arabic 63",
  "section": "Arabic",
  "number": "63",
  "exhort": "O SON OF MAN!",
  "text": "The light hath shone on thee from the horizon of the sacred Mount and the spirit of enlightenment hath breathed in the Sinai of thy heart. Wherefore, free thyself from the veils of idle fancies and enter into My court, that thou mayest be fit for everlasting life and worthy to meet Me. Thus may death not come upon thee, neither weariness nor trouble.",
  "teaser": "The light hath shone on thee...",
},
{
  "id": "Arabic64",
  "title": "Arabic 64",
  "section": "Arabic",
  "number": "64",
  "exhort": "O SON OF MAN!",
  "text": "My eternity is My creation, I have created it for thee. Make it the garment of thy temple. My unity is My handiwork; I have wrought it for thee; clothe thyself therewith, that thou mayest be to all eternity the revelation of My everlasting being.",
  "teaser": "My eternity is My creation...",
},
{
  "id": "Arabic65",
  "title": "Arabic 65",
  "section": "Arabic",
  "number": "65",
  "exhort": "O SON OF MAN!",
  "text": "My majesty is My gift to thee, and My grandeur the token of My mercy unto thee. That which beseemeth Me none shall understand, nor can anyone recount. Verily, I have preserved it in My hidden storehouses and in the treasuries of My command, as a sign of My loving-kindness unto My servants and My mercy unto My people.",
  "teaser": "My majesty is My gift to thee...",
},
{
  "id": "Arabic66",
  "title": "Arabic 66",
  "section": "Arabic",
  "number": "66",
  "exhort": "O CHILDREN OF THE DIVINE AND INVISIBLE ESSENCE!",
  "text": "Ye shall be hindered from loving Me and souls shall be perturbed as they make mention of Me. For minds cannot grasp Me nor hearts contain Me.",
},
{
  "id": "Arabic67",
  "title": "Arabic 67",
  "section": "Arabic",
  "number": "67",
  "exhort": "O SON OF BEAUTY!",
  "text": "By My spirit and by My favor! By My mercy and by My beauty! All that I have revealed unto thee with the tongue of power, and have written for thee with the pen of might, hath been in accordance with thy capacity and understanding, not with My state and the melody of My voice.",
  "teaser": "By My spirit and by My favor...",
},
{
  "id": "Arabic68",
  "title": "Arabic 68",
  "section": "Arabic",
  "number": "68",
  "exhort": "O CHILDREN OF MEN!",
  "text": "Know ye not why We created you all from the same dust? That no one should exalt himself over the other. Ponder at all times in your hearts how ye were created. Since We have created you all from one same substance it is incumbent on you to be even as one soul, to walk with the same feet, eat with the same mouth and dwell in the same land, that from your inmost being, by your deeds and actions, the signs of oneness and the essence of detachment may be made manifest. Such is My counsel to you, O concourse of light! Heed ye this counsel that ye may obtain the fruit of holiness from the tree of wondrous glory.",
  "teaser": "Know ye not why We created...",
},
{
  "id": "Arabic69",
  "title": "Arabic 69",
  "section": "Arabic",
  "number": "69",
  "exhort": "O YE SONS OF SPIRIT!",
  "text": "Ye are My treasury, for in you I have treasured the pearls of My mysteries and the gems of My knowledge. Guard them from the strangers amidst My servants and from the ungodly amongst My people.",
  "teaser": "Ye are My treasury...",
},
{
  "id": "Arabic70",
  "title": "Arabic 70",
  "section": "Arabic",
  "number": "70",
  "exhort": "O SON OF HIM THAT STOOD BY HIS OWN ENTITY IN THE KINGDOM OF HIS SELF!",
  "text": "Know thou, that I have wafted unto thee all the fragrances of holiness, have fully revealed to thee My word, have perfected through thee My bounty and have desired for thee that which I have desired for My Self. Be then content with My pleasure and thankful unto Me.",
  "teaser": "O SON OF HIM THAT STOOD BY HIS OWN ENTITY...",
},
{
  "id": "Arabic71",
  "title": "Arabic 71",
  "section": "Arabic",
  "number": "71",
  "exhort": "O SON OF MAN!",
  "text": "Write all that We have revealed unto thee with the ink of light upon the tablet of thy spirit. Should this not be in thy power, then make thine ink of the essence of thy heart. If this thou canst not do, then write with that crimson ink that hath been shed in My path. Sweeter indeed is this to Me than all else, that its light may endure forever.",
  "teaser": "Write all that We have revealed...",
},
{
  "id": "Persian01",
  "title": "Persian 1",
  "section": "Persian",
  "number": "1",
  "pretext": "In the Name of the Lord of Utterance, the Mighty.",
  "exhort": "O YE PEOPLE THAT HAVE MINDS TO KNOW AND EARS TO HEAR!",
  "text": "The first call of the Beloved is this: O mystic nightingale! Abide not but in the rose garden of the spirit. O messenger of the Solomon of love! Seek thou no shelter except in the Sheba of the well-beloved, and O immortal phoenix! dwell not save on the mount of faithfulness. Therein is thy habitation, if on the wings of thy soul thou soarest to the realm of the infinite and seekest to attain thy goal.",
  "teaser": "O YE PEOPLE THAT HAVE MINDS TO KNOW...",
},
{
  "id": "Persian02",
  "title": "Persian 2",
  "section": "Persian",
  "number": "2",
  "exhort": "O SON OF SPIRIT!",
  "text": "The bird seeketh its nest; the nightingale the charm of the rose; whilst those birds, the hearts of men, content with transient dust, have strayed far from their eternal nest, and with eyes turned towards the slough of heedlessness are bereft of the glory of the divine presence. Alas! How strange and pitiful; for a mere cupful, they have turned away from the billowing seas of the Most High, and remained far from the most effulgent horizon.",
  "teaser": "The bird seeketh its nest...",
},
{
  "id": "Persian03",
  "title": "Persian 3",
  "section": "Persian",
  "number": "3",
  "exhort": "O FRIEND!",
  "text": "In the garden of thy heart plant naught but the rose of love, and from the nightingale of affection and desire loosen not thy hold. Treasure the companionship of the righteous and eschew all fellowship with the ungodly.",
  "teaser": "In the garden of thy heart...",
},
{
  "id": "Persian04",
  "title": "Persian 4",
  "section": "Persian",
  "number": "4",
  "exhort": "O SON OF JUSTICE!",
  "text": "Whither can a lover go but to the land of his beloved? and what seeker findeth rest away from his heart’s desire? To the true lover reunion is life, and separation is death. His breast is void of patience and his heart hath no peace. A myriad lives he would forsake to hasten to the abode of his beloved.",
  "teaser": "Whither can a lover go...",
},
{
  "id": "Persian05",
  "title": "Persian 5",
  "section": "Persian",
  "number": "5",
  "exhort": "O SON OF DUST!",
  "text": "Verily I say unto thee: Of all men the most negligent is he that disputeth idly and seeketh to advance himself over his brother. Say: O brethren! Let deeds, not words, be your adorning.",
  "teaser": "Verily I say unto thee...",
},
{
  "id": "Persian06",
  "title": "Persian 6",
  "section": "Persian",
  "number": "6",
  "exhort": "O SON OF EARTH!",
  "text": "Know, verily, the heart wherein the least remnant of envy yet lingers, shall never attain My everlasting dominion, nor inhale the sweet savors of holiness breathing from My kingdom of sanctity.",
  "teaser": "Know, verily, the heart...",
},
{
  "id": "Persian07",
  "title": "Persian 7",
  "section": "Persian",
  "number": "7",
  "exhort": "O SON OF LOVE!",
  "text": "Thou art but one step away from the glorious heights above and from the celestial tree of love. Take thou one pace and with the next advance into the immortal realm and enter the pavilion of eternity. Give ear then to that which hath been revealed by the Pen of Glory.",
  "teaser": "Thou art but one step away...",
},
{
  "id": "Persian08",
  "title": "Persian 8",
  "section": "Persian",
  "number": "8",
  "exhort": "O SON OF GLORY!",
  "text": "Be swift in the path of holiness, and enter the heaven of communion with Me. Cleanse thy heart with the burnish of the spirit, and hasten to the court of the Most High.",
  "teaser": "Be swift in the path...",
},
{
  "id": "Persian09",
  "title": "Persian 9",
  "section": "Persian",
  "number": "9",
  "exhort": "O FLEETING SHADOW!",
  "text": "Pass beyond the baser stages of doubt and rise to the exalted heights of certainty. Open the eye of truth, that thou mayest behold the veilless Beauty and exclaim: Hallowed be the Lord, the most excellent of all creators!",
  "teaser": "Pass beyond the baser stages...",
},
{
  "id": "Persian10",
  "title": "Persian 10",
  "section": "Persian",
  "number": "10",
  "exhort": "O SON OF DESIRE!",
  "text": "Give ear unto this: Never shall mortal eye recognize the everlasting Beauty, nor the lifeless heart delight in aught but in the withered bloom. For like seeketh like, and taketh pleasure in the company of its kind.",
  "teaser": "Give ear unto this: Never...",
},
{
  "id": "Persian11",
  "title": "Persian 11",
  "section": "Persian",
  "number": "11",
  "exhort": "O SON OF DUST!",
  "text": "Blind thine eyes, that thou mayest behold My beauty; stop thine ears, that thou mayest hearken unto the sweet melody of My voice; empty thyself of all learning, that thou mayest partake of My knowledge; and sanctify thyself from riches, that thou mayest obtain a lasting share from the ocean of My eternal wealth. Blind thine eyes, that is, to all save My beauty; stop thine ears to all save My word; empty thyself of all learning save the knowledge of Me; that with a clear vision, a pure heart and an attentive ear thou mayest enter the court of My holiness.",
  "teaser": "Blind thine eyes...",
},
{
  "id": "Persian12",
  "title": "Persian 12",
  "section": "Persian",
  "number": "12",
  "exhort": "O MAN OF TWO VISIONS!",
  "text": "Close one eye and open the other. Close one to the world and all that is therein, and open the other to the hallowed beauty of the Beloved.",
  "teaser": "Close one eye...",
},
{
  "id": "Persian13",
  "title": "Persian 13",
  "section": "Persian",
  "number": "13",
  "exhort": "O MY CHILDREN!",
  "text": "I fear lest, bereft of the melody of the dove of heaven, ye will sink back to the shades of utter loss, and, never having gazed upon the beauty of the rose, return to water and clay.",
  "teaser": "I fear lest, bereft of the melody...",
},
{
  "id": "Persian14",
  "title": "Persian 14",
  "section": "Persian",
  "number": "14",
  "exhort": "O FRIENDS!",
  "text": "Abandon not the everlasting beauty for a beauty that must die, and set not your affections on this mortal world of dust.",
  "teaser": "Abandon not the everlasting beauty...",
},
{
  "id": "Persian15",
  "title": "Persian 15",
  "section": "Persian",
  "number": "15",
  "exhort": "O SON OF SPIRIT!",
  "text": "The time cometh, when the nightingale of holiness will no longer unfold the inner mysteries and ye will all be bereft of the celestial melody and of the voice from on high.",
  "teaser": "The time cometh, when the nightingale...",
},
{
  "id": "Persian16",
  "title": "Persian 16",
  "section": "Persian",
  "number": "16",
  "exhort": "O ESSENCE OF NEGLIGENCE!",
  "text": "Myriads of mystic tongues find utterance in one speech, and myriads of hidden mysteries are revealed in a single melody; yet, alas, there is no ear to hear, nor heart to understand.",
  "teaser": "Myriads of mystic tongues...",
},
{
  "id": "Persian17",
  "title": "Persian 17",
  "section": "Persian",
  "number": "17",
  "exhort": "O COMRADES!",
  "text": "The gates that open on the Placeless stand wide and the habitation of the loved one is adorned with the lovers’ blood, yet all but a few remain bereft of this celestial city, and even of these few, none but the smallest handful hath been found with a pure heart and sanctified spirit.",
  "teaser": "The gates that open on the Placeless...",
},
{
  "id": "Persian18",
  "title": "Persian 18",
  "section": "Persian",
  "number": "18",
  "exhort": "O YE DWELLERS IN THE HIGHEST PARADISE!",
  "text": "Proclaim unto the children of assurance that within the realms of holiness, nigh unto the celestial paradise, a new garden hath appeared, round which circle the denizens of the realm on high and the immortal dwellers of the exalted paradise. Strive, then, that ye may attain that station, that ye may unravel the mysteries of love from its windflowers and learn the secret of divine and consummate wisdom from its eternal fruits. Solaced are the eyes of them that enter and abide therein!",
},
{
  "id": "Persian19",
  "title": "Persian 19",
  "section": "Persian",
  "number": "19",
  "exhort": "O MY FRIENDS!",
  "text": "Have ye forgotten that true and radiant morn, when in those hallowed and blessed surroundings ye were all gathered in My presence beneath the shade of the tree of life, which is planted in the all-glorious paradise? Awestruck ye listened as I gave utterance to these three most holy words: O friends! Prefer not your will to Mine, never desire that which I have not desired for you, and approach Me not with lifeless hearts, defiled with worldly desires and cravings. Would ye but sanctify your souls, ye would at this present hour recall that place and those surroundings, and the truth of My utterance should be made evident unto all of you.",
  "teaser": "Have ye forgotten...",
},
{
  "id": "Persian20",
  "title": "Persian 20",
  "section": "Persian",
  "number": "20",
  "pretext": "In the eighth of the most holy lines, in the fifth Tablet of Paradise, He saith:",
  "exhort": "O YE THAT ARE LYING AS DEAD ON THE COUCH OF HEEDLESSNESS!",
  "text": "Ages have passed and your precious lives are well-nigh ended, yet not a single breath of purity hath reached Our court of holiness from you. Though immersed in the ocean of misbelief, yet with your lips ye profess the one true faith of God. Him whom I abhor ye have loved, and of My foe ye have made a friend. Notwithstanding, ye walk on My earth complacent and self-satisfied, heedless that My earth is weary of you and everything within it shunneth you. Were ye but to open your eyes, ye would, in truth, prefer a myriad griefs unto this joy, and would count death itself better than this life.",
},
{
  "id": "Persian21",
  "title": "Persian 21",
  "section": "Persian",
  "number": "21",
  "exhort": "O MOVING FORM OF DUST!",
  "text": "I desire communion with thee, but thou wouldst put no trust in Me. The sword of thy rebellion hath felled the tree of thy hope. At all times I am near unto thee, but thou art ever far from Me. Imperishable glory I have chosen for thee, yet boundless shame thou hast chosen for thyself. While there is yet time, return, and lose not thy chance.",
  "teaser": "I desire communion with thee...",
},
{
  "id": "Persian22",
  "title": "Persian 22",
  "section": "Persian",
  "number": "22",
  "exhort": "O SON OF DESIRE!",
  "text": "The learned and the wise have for long years striven and failed to attain the presence of the All-Glorious; they have spent their lives in search of Him, yet did not behold the beauty of His countenance. Thou without the least effort didst attain thy goal, and without search hast obtained the object of thy quest. Yet, notwithstanding, thou didst remain so wrapt in the veil of self, that thine eyes beheld not the beauty of the Beloved, nor did thy hand touch the hem of His robe. Ye that have eyes, behold and wonder.",
  "teaser": "The learned and the wise...",
},
{
  "id": "Persian23",
  "title": "Persian 23",
  "section": "Persian",
  "number": "23",
  "exhort": "O DWELLERS IN THE CITY OF LOVE!",
  "text": "Mortal blasts have beset the everlasting candle, and the beauty of the celestial Youth is veiled in the darkness of dust. The chief of the monarchs of love is wronged by the people of tyranny and the dove of holiness lies prisoned in the talons of owls. The dwellers in the pavilion of glory and the celestial concourse bewail and lament, while ye repose in the realm of negligence, and esteem yourselves as of the true friends. How vain are your imaginings!",
  "teaser": "Mortal blasts have beset...",
},
{
  "id": "Persian24",
  "title": "Persian 24",
  "section": "Persian",
  "number": "24",
  "exhort": "O YE THAT ARE FOOLISH, YET HAVE A NAME TO BE WISE!",
  "text": "Wherefore do ye wear the guise of shepherds, when inwardly ye have become wolves, intent upon My flock? Ye are even as the star, which riseth ere the dawn, and which, though it seem radiant and luminous, leadeth the wayfarers of My city astray into the paths of perdition.",
},
{
  "id": "Persian25",
  "title": "Persian 25",
  "section": "Persian",
  "number": "25",
  "exhort": "O YE SEEMING FAIR YET INWARDLY FOUL!",
  "text": "Ye are like clear but bitter water, which to outward seeming is crystal pure but of which, when tested by the divine Assayer, not a drop is accepted. Yea, the sunbeam falls alike upon the dust and the mirror, yet differ they in reflection even as doth the star from the earth: nay, immeasurable is the difference!",
},
{
  "id": "Persian26",
  "title": "Persian 26",
  "section": "Persian",
  "number": "26",
  "exhort": "O MY FRIEND IN WORD!",
  "text": "Ponder awhile. Hast thou ever heard that friend and foe should abide in one heart? Cast out then the stranger, that the Friend may enter His home.",
  "teaser": "Ponder awhile...",
},
{
  "id": "Persian27",
  "title": "Persian 27",
  "section": "Persian",
  "number": "27",
  "exhort": "O SON OF DUST!",
  "text": "All that is in heaven and earth I have ordained for thee, except the human heart, which I have made the habitation of My beauty and glory; yet thou didst give My home and dwelling to another than Me; and whenever the manifestation of My holiness sought His own abode, a stranger found He there, and, homeless, hastened unto the sanctuary of the Beloved. Notwithstanding I have concealed thy secret and desired not thy shame.",
  "teaser": "All that is in heaven and earth...",
},
{
  "id": "Persian28",
  "title": "Persian 28",
  "section": "Persian",
  "number": "28",
  "exhort": "O ESSENCE OF DESIRE!",
  "text": "At many a dawn have I turned from the realms of the Placeless unto thine abode, and found thee on the bed of ease busied with others than Myself. Thereupon, even as the flash of the spirit, I returned to the realms of celestial glory and breathed it not in My retreats above unto the hosts of holiness.",
  "teaser": "At many a dawn have I turned...",
},
{
  "id": "Persian29",
  "title": "Persian 29",
  "section": "Persian",
  "number": "29",
  "exhort": "O SON OF BOUNTY!",
  "text": "Out of the wastes of nothingness, with the clay of My command I made thee to appear, and have ordained for thy training every atom in existence and the essence of all created things. Thus, ere thou didst issue from thy mother’s womb, I destined for thee two founts of gleaming milk, eyes to watch over thee, and hearts to love thee. Out of My loving-kindness, ’neath the shade of My mercy I nurtured thee, and guarded thee by the essence of My grace and favor. And My purpose in all this was that thou mightest attain My everlasting dominion and become worthy of My invisible bestowals. And yet heedless thou didst remain, and when fully grown, thou didst neglect all My bounties and occupied thyself with thine idle imaginings, in such wise that thou didst become wholly forgetful, and, turning away from the portals of the Friend didst abide within the courts of My enemy.",
  "teaser": "Out of the wastes of nothingness...",
},
{
  "id": "Persian30",
  "title": "Persian 30",
  "section": "Persian",
  "number": "30",
  "exhort": "O BONDSLAVE OF THE WORLD!",
  "text": "Many a dawn hath the breeze of My loving-kindness wafted over thee and found thee upon the bed of heedlessness fast asleep. Bewailing then thy plight it returned whence it came.",
  "teaser": "Many a dawn...",
},
{
  "id": "Persian31",
  "title": "Persian 31",
  "section": "Persian",
  "number": "31",
  "exhort": "O SON OF EARTH!",
  "text": "Wouldst thou have Me, seek none other than Me; and wouldst thou gaze upon My beauty, close thine eyes to the world and all that is therein; for My will and the will of another than Me, even as fire and water, cannot dwell together in one heart.",
  "teaser": "Wouldst thou have Me...",
},
{
  "id": "Persian32",
  "title": "Persian 32",
  "section": "Persian",
  "number": "32",
  "exhort": "O BEFRIENDED STRANGER!",
  "text": "The candle of thine heart is lighted by the hand of My power, quench it not with the contrary winds of self and passion. The healer of all thine ills is remembrance of Me, forget it not. Make My love thy treasure and cherish it even as thy very sight and life.",
  "teaser": "The candle of thine heart...",
},
{
  "id": "Persian33",
  "title": "Persian 33",
  "section": "Persian",
  "number": "33",
  "exhort": "O MY BROTHER!",
  "text": "Hearken to the delightsome words of My honeyed tongue, and quaff the stream of mystic holiness from My sugar-shedding lips. Sow the seeds of My divine wisdom in the pure soil of thy heart, and water them with the water of certitude, that the hyacinths of My knowledge and wisdom may spring up fresh and green in the sacred city of thy heart.",
  "teaser": "Hearken to the delightsome words...",
},
{
  "id": "Persian34",
  "title": "Persian 34",
  "section": "Persian",
  "number": "34",
  "exhort": "O DWELLERS OF MY PARADISE!",
  "text": "With the hands of loving-kindness I have planted in the holy garden of paradise the young tree of your love and friendship, and have watered it with the goodly showers of My tender grace; now that the hour of its fruiting is come, strive that it may be protected, and be not consumed with the flame of desire and passion.",
  "teaser": "With the hands...",
},
{
  "id": "Persian35",
  "title": "Persian 35",
  "section": "Persian",
  "number": "35",
  "exhort": "O MY FRIENDS!",
  "text": "Quench ye the lamp of error, and kindle within your hearts the everlasting torch of divine guidance. For ere long the assayers of mankind shall, in the holy presence of the Adored, accept naught but purest virtue and deeds of stainless holiness.",
  "teaser": "Quench ye the lamp of error...",
},
{
  "id": "Persian36",
  "title": "Persian 36",
  "section": "Persian",
  "number": "36",
  "exhort": "O SON OF DUST!",
  "text": "The wise are they that speak not unless they obtain a hearing, even as the cup-bearer, who proffereth not his cup till he findeth a seeker, and the lover who crieth not out from the depths of his heart until he gazeth upon the beauty of his beloved. Wherefore sow the seeds of wisdom and knowledge in the pure soil of the heart, and keep them hidden, till the hyacinths of divine wisdom spring from the heart and not from mire and clay.",
  "teaser": "The wise are they that speak not...",
},
{
  "id": "Persian37",
  "title": "Persian 37",
  "section": "Persian",
  "number": "37",
  "pretext": "In the first line of the Tablet it is recorded and written, and within the sanctuary of the tabernacle of God is hidden:",
  "exhort": "O MY SERVANT!",
  "text": "Abandon not for that which perisheth an everlasting dominion, and cast not away celestial sovereignty for a worldly desire. This is the river of everlasting life that hath flowed from the wellspring of the pen of the merciful; well is it with them that drink!",
  "teaser": "Abandon not for that which perisheth...",
},
{
  "id": "Persian38",
  "title": "Persian 38",
  "section": "Persian",
  "number": "38",
  "exhort": "O SON OF SPIRIT!",
  "text": "Burst thy cage asunder, and even as the phoenix of love soar into the firmament of holiness. Renounce thyself and, filled with the spirit of mercy, abide in the realm of celestial sanctity.",
  "teaser": "Burst thy cage asunder...",
},
{
  "id": "Persian39",
  "title": "Persian 39",
  "section": "Persian",
  "number": "39",
  "exhort": "O OFFSPRING OF DUST!",
  "text": "Be not content with the ease of a passing day, and deprive not thyself of everlasting rest. Barter not the garden of eternal delight for the dust-heap of a mortal world. Up from thy prison ascend unto the glorious meads above, and from thy mortal cage wing thy flight unto the paradise of the Placeless.",
  "teaser": "Be not content with the ease...",
},
{
  "id": "Persian40",
  "title": "Persian 40",
  "section": "Persian",
  "number": "40",
  "exhort": "O MY SERVANT!",
  "text": "Free thyself from the fetters of this world, and loose thy soul from the prison of self. Seize thy chance, for it will come to thee no more.",
  "teaser": "Free thyself from the fetters...",
},
{
  "id": "Persian41",
  "title": "Persian 41",
  "section": "Persian",
  "number": "41",
  "exhort": "O SON OF MY HANDMAID!",
  "text": "Didst thou behold immortal sovereignty, thou wouldst strive to pass from this fleeting world. But to conceal the one from thee and to reveal the other is a mystery which none but the pure in heart can comprehend.",
  "teaser": "Didst thou behold immortal sovereignty...",
},
{
  "id": "Persian42",
  "title": "Persian 42",
  "section": "Persian",
  "number": "42",
  "exhort": "O MY SERVANT!",
  "text": "Purge thy heart from malice and, innocent of envy, enter the divine court of holiness.",
  "teaser": "Purge thy heart from malice...",
},
{
  "id": "Persian43",
  "title": "Persian 43",
  "section": "Persian",
  "number": "43",
  "exhort": "O MY FRIENDS!",
  "text": "Walk ye in the ways of the good pleasure of the Friend, and know that His pleasure is in the pleasure of His creatures. That is: no man should enter the house of his friend save at his friend’s pleasure, nor lay hands upon his treasures nor prefer his own will to his friend’s, and in no wise seek an advantage over him. Ponder this, ye that have insight!",
  "teaser": "Walk ye in the ways...",
},
{
  "id": "Persian44",
  "title": "Persian 44",
  "section": "Persian",
  "number": "44",
  "exhort": "O COMPANION OF MY THRONE!",
  "text": "Hear no evil, and see no evil, abase not thyself, neither sigh and weep. Speak no evil, that thou mayest not hear it spoken unto thee, and magnify not the faults of others that thine own faults may not appear great; and wish not the abasement of anyone, that thine own abasement be not exposed. Live then the days of thy life, that are less than a fleeting moment, with thy mind stainless, thy heart unsullied, thy thoughts pure, and thy nature sanctified, so that, free and content, thou mayest put away this mortal frame, and repair unto the mystic paradise and abide in the eternal kingdom forevermore.",
  "teaser": "Hear no evil...",
},
{
  "id": "Persian45",
  "title": "Persian 45",
  "section": "Persian",
  "number": "45",
  "exhort": "ALAS! ALAS! O LOVERS OF WORLDLY DESIRE!",
  "text": "Even as the swiftness of lightning ye have passed by the Beloved One, and have set your hearts on satanic fancies. Ye bow the knee before your vain imagining, and call it truth. Ye turn your eyes towards the thorn, and name it a flower. Not a pure breath have ye breathed, nor hath the breeze of detachment been wafted from the meadows of your hearts. Ye have cast to the winds the loving counsels of the Beloved and have effaced them utterly from the tablet of your hearts, and even as the beasts of the field, ye move and have your being within the pastures of desire and passion.",
},
{
  "id": "Persian46",
  "title": "Persian 46",
  "section": "Persian",
  "number": "46",
  "exhort": "O BRETHREN IN THE PATH!",
  "text": "Wherefore have ye neglected the mention of the Loved One, and kept remote from His holy presence? The essence of beauty is within the peerless pavilion, set upon the throne of glory, whilst ye busy yourselves with idle contentions. The sweet savors of holiness are breathing and the breath of bounty is wafted, yet ye are all sorely afflicted and deprived thereof. Alas for you and for them that walk in your ways and follow in your footsteps!",
  "teaser": "Wherefore have ye neglected...",
},
{
  "id": "Persian47",
  "title": "Persian 47",
  "section": "Persian",
  "number": "47",
  "exhort": "O CHILDREN OF DESIRE!",
  "text": "Put away the garment of vainglory, and divest yourselves of the attire of haughtiness.",
  "teaser": "Put away the garment of vainglory...",
},
{
  "id": "Persian48",
  "title": "Persian 48",
  "section": "Persian",
  "number": "48",
  "pretext": "In the third of the most holy lines writ and recorded in the Ruby Tablet by the pen of the unseen this is revealed:",
  "exhort": "O BRETHREN!",
  "text": "Be forbearing one with another and set not your affections on things below. Pride not yourselves in your glory, and be not ashamed of abasement. By My beauty! I have created all things from dust, and to dust will I return them again.",
  "teaser": "Be forbearing one with another...",
},
{
  "id": "Persian49",
  "title": "Persian 49",
  "section": "Persian",
  "number": "49",
  "exhort": "O CHILDREN OF DUST!",
  "text": "Tell the rich of the midnight sighing of the poor, lest heedlessness lead them into the path of destruction, and deprive them of the Tree of Wealth. To give and to be generous are attributes of Mine; well is it with him that adorneth himself with My virtues.",
  "teaser": "Tell the rich...",
},
{
  "id": "Persian50",
  "title": "Persian 50",
  "section": "Persian",
  "number": "50",
  "exhort": "O QUINTESSENCE OF PASSION!",
  "text": "Put away all covetousness and seek contentment; for the covetous hath ever been deprived, and the contented hath ever been loved and praised.",
  "teaser": "Put away all covetousness...",
},
{
  "id": "Persian51",
  "title": "Persian 51",
  "section": "Persian",
  "number": "51",
  "exhort": "O SON OF MY HANDMAID!",
  "text": "Be not troubled in poverty nor confident in riches, for poverty is followed by riches, and riches are followed by poverty. Yet to be poor in all save God is a wondrous gift, belittle not the value thereof, for in the end it will make thee rich in God, and thus thou shalt know the meaning of the utterance, “In truth ye are the poor,” and the holy words, “God is the all-possessing,” shall even as the true morn break forth gloriously resplendent upon the horizon of the lover’s heart, and abide secure on the throne of wealth.",
  "teaser": "Be not troubled in poverty...",
},
{
  "id": "Persian52",
  "title": "Persian 52",
  "section": "Persian",
  "number": "52",
  "exhort": "O CHILDREN OF NEGLIGENCE AND PASSION!",
  "text": "Ye have suffered My enemy to enter My house and have cast out My friend, for ye have enshrined the love of another than Me in your hearts. Give ear to the sayings of the Friend and turn towards His paradise. Worldly friends, seeking their own good, appear to love one the other, whereas the true Friend hath loved and doth love you for your own sakes; indeed He hath suffered for your guidance countless afflictions. Be not disloyal to such a Friend, nay rather hasten unto Him. Such is the daystar of the word of truth and faithfulness, that hath dawned above the horizon of the pen of the Lord of all names. Open your ears that ye may hearken unto the word of God, the Help in peril, the Self-Existent.",
},
{
  "id": "Persian53",
  "title": "Persian 53",
  "section": "Persian",
  "number": "53",
  "exhort": "O YE THAT PRIDE YOURSELVES ON MORTAL RICHES!",
  "text": "Know ye in truth that wealth is a mighty barrier between the seeker and his desire, the lover and his beloved. The rich, but for a few, shall in no wise attain the court of His presence nor enter the city of content and resignation. Well is it then with him, who, being rich, is not hindered by his riches from the eternal kingdom, nor deprived by them of imperishable dominion. By the Most Great Name! The splendor of such a wealthy man shall illuminate the dwellers of heaven even as the sun enlightens the people of the earth!",
},
{
  "id": "Persian54",
  "title": "Persian 54",
  "section": "Persian",
  "number": "54",
  "exhort": "O YE RICH ONES ON EARTH!",
  "text": "The poor in your midst are My trust; guard ye My trust, and be not intent only on your own ease.",
  "teaser": "The poor in your midst...",
},
{
  "id": "Persian55",
  "title": "Persian 55",
  "section": "Persian",
  "number": "55",
  "exhort": "O SON OF PASSION!",
  "text": "Cleanse thyself from the defilement of riches and in perfect peace advance into the realm of poverty; that from the wellspring of detachment thou mayest quaff the wine of immortal life.",
  "teaser": "Cleanse thyself from the defilement...",
},
{
  "id": "Persian56",
  "title": "Persian 56",
  "section": "Persian",
  "number": "56",
  "exhort": "O MY SON!",
  "text": "The company of the ungodly increaseth sorrow, whilst fellowship with the righteous cleanseth the rust from off the heart. He that seeketh to commune with God, let him betake himself to the companionship of His loved ones; and he that desireth to hearken unto the word of God, let him give ear to the words of His chosen ones.",
  "teaser": "The company of the ungodly...",
},
{
  "id": "Persian57",
  "title": "Persian 57",
  "section": "Persian",
  "number": "57",
  "exhort": "O SON OF DUST!",
  "text": "Beware! Walk not with the ungodly and seek not fellowship with him, for such companionship turneth the radiance of the heart into infernal fire.",
  "teaser": "Beware! Walk not with the ungodly...",
},
{
  "id": "Persian58",
  "title": "Persian 58",
  "section": "Persian",
  "number": "58",
  "exhort": "O SON OF MY HANDMAID!",
  "text": "Wouldst thou seek the grace of the Holy Spirit, enter into fellowship with the righteous, for he hath drunk the cup of eternal life at the hands of the immortal Cupbearer and even as the true morn doth quicken and illumine the hearts of the dead.",
  "teaser": "Wouldst thou seek the grace...",
},
{
  "id": "Persian59",
  "title": "Persian 59",
  "section": "Persian",
  "number": "59",
  "exhort": "O HEEDLESS ONES!",
  "text": "Think not the secrets of hearts are hidden, nay, know ye of a certainty that in clear characters they are engraved and are openly manifest in the holy Presence.",
  "teaser": "Think not the secrets of hearts...",
},
{
  "id": "Persian60",
  "title": "Persian 60",
  "section": "Persian",
  "number": "60",
  "exhort": "O FRIENDS!",
  "text": "Verily I say, whatsoever ye have concealed within your hearts is to Us open and manifest as the day; but that it is hidden is of Our grace and favor, and not of your deserving.",
  "teaser": "Verily I say, whatsoever ye have concealed...",
},
{
  "id": "Persian61",
  "title": "Persian 61",
  "section": "Persian",
  "number": "61",
  "exhort": "O SON OF MAN!",
  "text": "A dewdrop out of the fathomless ocean of My mercy I have shed upon the peoples of the world, yet found none turn thereunto, inasmuch as everyone hath turned away from the celestial wine of unity unto the foul dregs of impurity, and, content with mortal cup, hath put away the chalice of immortal beauty. Vile is that wherewith he is contented.",
  "teaser": "A dewdrop out of the fathomless ocean...",
},
{
  "id": "Persian62",
  "title": "Persian 62",
  "section": "Persian",
  "number": "62",
  "exhort": "O SON OF DUST!",
  "text": "Turn not away thine eyes from the matchless wine of the immortal Beloved, and open them not to foul and mortal dregs. Take from the hands of the divine Cupbearer the chalice of immortal life, that all wisdom may be thine, and that thou mayest hearken unto the mystic voice calling from the realm of the invisible. Cry aloud, ye that are of low aim! Wherefore have ye turned away from My holy and immortal wine unto evanescent water?",
  "teaser": "Turn not away thine eyes...",
},
{
  "id": "Persian63",
  "title": "Persian 63",
  "section": "Persian",
  "number": "63",
  "exhort": "O YE PEOPLES OF THE WORLD!",
  "text": "Know, verily, that an unforeseen calamity followeth you, and grievous retribution awaiteth you. Think not that which ye have committed hath been effaced in My sight. By My beauty! All your doings hath My pen graven with open characters upon tablets of chrysolite.",
  "teaser": "Know, verily...",
},
{
  "id": "Persian64",
  "title": "Persian 64",
  "section": "Persian",
  "number": "64",
  "exhort": "O OPPRESSORS ON EARTH!",
  "text": "Withdraw your hands from tyranny, for I have pledged Myself not to forgive any man’s injustice. This is My covenant which I have irrevocably decreed in the preserved tablet and sealed with My seal of glory.",
  "teaser": "Withdraw your hands...",
},
{
  "id": "Persian65",
  "title": "Persian 65",
  "section": "Persian",
  "number": "65",
  "exhort": "O REBELLIOUS ONES!",
  "text": "My forbearance hath emboldened you and My long-suffering hath made you negligent, in such wise that ye have spurred on the fiery charger of passion into perilous ways that lead unto destruction. Have ye thought Me heedless or that I was unaware?",
  "teaser": "My forbearance...",
},
{
  "id": "Persian66",
  "title": "Persian 66",
  "section": "Persian",
  "number": "66",
  "exhort": "O EMIGRANTS!",
  "text": "The tongue I have designed for the mention of Me, defile it not with detraction. If the fire of self overcome you, remember your own faults and not the faults of My creatures, inasmuch as every one of you knoweth his own self better than he knoweth others.",
  "teaser": "The tongue I have designed...",
},
{
  "id": "Persian67",
  "title": "Persian 67",
  "section": "Persian",
  "number": "67",
  "exhort": "O CHILDREN OF FANCY!",
  "text": "Know, verily, that while the radiant dawn breaketh above the horizon of eternal holiness, the satanic secrets and deeds done in the gloom of night shall be laid bare and manifest before the peoples of the world.",
  "teaser": "Know, verily, that while the radiant dawn...",
},
{
  "id": "Persian68",
  "title": "Persian 68",
  "section": "Persian",
  "number": "68",
  "exhort": "O WEED THAT SPRINGETH OUT OF DUST!",
  "text": "Wherefore have not these soiled hands of thine touched first thine own garment, and why with thine heart defiled with desire and passion dost thou seek to commune with Me and to enter My sacred realm? Far, far are ye from that which ye desire.",
  "teaser": "Wherefore have not...",
},
{
  "id": "Persian69",
  "title": "Persian 69",
  "section": "Persian",
  "number": "69",
  "exhort": "O CHILDREN OF ADAM!",
  "text": "Holy words and pure and goodly deeds ascend unto the heaven of celestial glory. Strive that your deeds may be cleansed from the dust of self and hypocrisy and find favor at the court of glory; for ere long the assayers of mankind shall, in the holy presence of the Adored One, accept naught but absolute virtue and deeds of stainless purity. This is the daystar of wisdom and of divine mystery that hath shone above the horizon of the divine will. Blessed are they that turn thereunto.",
  "teaser": "Holy words and pure and goodly deeds...",
},
{
  "id": "Persian70",
  "title": "Persian 70",
  "section": "Persian",
  "number": "70",
  "exhort": "O SON OF WORLDLINESS!",
  "text": "Pleasant is the realm of being, wert thou to attain thereto; glorious is the domain of eternity, shouldst thou pass beyond the world of mortality; sweet is the holy ecstasy if thou drinkest of the mystic chalice from the hands of the celestial Youth. Shouldst thou attain this station, thou wouldst be freed from destruction and death, from toil and sin.",
  "teaser": "Pleasant is the realm of being...",
},
{
  "id": "Persian71",
  "title": "Persian 71",
  "section": "Persian",
  "number": "71",
  "exhort": "O MY FRIENDS!",
  "text": "Call ye to mind that covenant ye have entered into with Me upon Mount Paran, situate within the hallowed precincts of Zamán. I have taken to witness the concourse on high and the dwellers in the city of eternity, yet now none do I find faithful unto the covenant. Of a certainty pride and rebellion have effaced it from the hearts, in such wise that no trace thereof remaineth. Yet knowing this, I waited and disclosed it not.",
  "teaser": "Call ye to mind that covenant...",
},
{
  "id": "Persian72",
  "title": "Persian 72",
  "section": "Persian",
  "number": "72",
  "exhort": "O MY SERVANT!",
  "text": "Thou art even as a finely tempered sword concealed in the darkness of its sheath and its value hidden from the artificer’s knowledge. Wherefore come forth from the sheath of self and desire that thy worth may be made resplendent and manifest unto all the world.",
  "teaser": "Thou art even as a finely tempered sword...",
},
{
  "id": "Persian73",
  "title": "Persian 73",
  "section": "Persian",
  "number": "73",
  "exhort": "O MY FRIEND!",
  "text": "Thou art the daystar of the heavens of My holiness, let not the defilement of the world eclipse thy splendor. Rend asunder the veil of heedlessness, that from behind the clouds thou mayest emerge resplendent and array all things with the apparel of life.",
  "teaser": "Thou art the daystar of the heavens...",
},
{
  "id": "Persian74",
  "title": "Persian 74",
  "section": "Persian",
  "number": "74",
  "exhort": "O CHILDREN OF VAINGLORY!",
  "text": "For a fleeting sovereignty ye have abandoned My imperishable dominion, and have adorned yourselves with the gay livery of the world and made of it your boast. By My beauty! All will I gather beneath the one-colored covering of the dust and efface all these diverse colors save them that choose My own, and that is purging from every color.",
  "teaser": "For a fleeting sovereignty...",
},
{
  "id": "Persian75",
  "title": "Persian 75",
  "section": "Persian",
  "number": "75",
  "exhort": "O CHILDREN OF NEGLIGENCE!",
  "text": "Set not your affections on mortal sovereignty and rejoice not therein. Ye are even as the unwary bird that with full confidence warbleth upon the bough; till of a sudden the fowler Death throws it upon the dust, and the melody, the form and the color are gone, leaving not a trace. Wherefore take heed, O bondslaves of desire!",
  "teaser": "Set not your affections...",
},
{
  "id": "Persian76",
  "title": "Persian 76",
  "section": "Persian",
  "number": "76",
  "exhort": "O SON OF MY HANDMAID!",
  "text": "Guidance hath ever been given by words, and now it is given by deeds. Everyone must show forth deeds that are pure and holy, for words are the property of all alike, whereas such deeds as these belong only to Our loved ones. Strive then with heart and soul to distinguish yourselves by your deeds. In this wise We counsel you in this holy and resplendent tablet.",
  "teaser": "Guidance hath ever been given...",
},
{
  "id": "Persian77",
  "title": "Persian 77",
  "section": "Persian",
  "number": "77",
  "exhort": "O SON OF JUSTICE!",
  "text": "In the night-season the beauty of the immortal Being hath repaired from the emerald height of fidelity unto the Sadratu’l-Muntahá, and wept with such a weeping that the concourse on high and the dwellers of the realms above wailed at His lamenting. Whereupon there was asked, Why the wailing and weeping? He made reply: As bidden I waited expectant upon the hill of faithfulness, yet inhaled not from them that dwell on earth the fragrance of fidelity. Then summoned to return I beheld, and lo! certain doves of holiness were sore tried within the claws of the dogs of earth. Thereupon the Maid of heaven hastened forth unveiled and resplendent from Her mystic mansion, and asked of their names, and all were told but one. And when urged, the first letter thereof was uttered, whereupon the dwellers of the celestial chambers rushed forth out of their habitation of glory. And whilst the second letter was pronounced they fell down, one and all, upon the dust. At that moment a voice was heard from the inmost shrine: “Thus far and no farther.” Verily We bear witness to that which they have done and now are doing.",
  "teaser": "In the night-season the beauty...",
},
{
  "id": "Persian78",
  "title": "Persian 78",
  "section": "Persian",
  "number": "78",
  "exhort": "O SON OF MY HANDMAID!",
  "text": "Quaff from the tongue of the merciful the stream of divine mystery, and behold from the dayspring of divine utterance the unveiled splendor of the daystar of wisdom. Sow the seeds of My divine wisdom in the pure soil of the heart, and water them with the waters of certitude, that the hyacinths of knowledge and wisdom may spring up fresh and green from the holy city of the heart.",
  "teaser": "Quaff from the tongue...",
},
{
  "id": "Persian79",
  "title": "Persian 79",
  "section": "Persian",
  "number": "79",
  "exhort": "O SON OF DESIRE!",
  "text": "How long wilt thou soar in the realms of desire? Wings have I bestowed upon thee, that thou mayest fly to the realms of mystic holiness and not the regions of satanic fancy. The comb, too, have I given thee that thou mayest dress My raven locks, and not lacerate My throat.",
  "teaser": "How long wilt thou soar...",
},
{
  "id": "Persian80",
  "title": "Persian 80",
  "section": "Persian",
  "number": "80",
  "exhort": "O MY SERVANTS!",
  "text": "Ye are the trees of My garden; ye must give forth goodly and wondrous fruits, that ye yourselves and others may profit therefrom. Thus it is incumbent on every one to engage in crafts and professions, for therein lies the secret of wealth, O men of understanding! For results depend upon means, and the grace of God shall be all-sufficient unto you. Trees that yield no fruit have been and will ever be for the fire.",
  "teaser": "Ye are the trees of My garden...",
},
{
  "id": "Persian81",
  "title": "Persian 81",
  "section": "Persian",
  "number": "81",
  "exhort": "O MY SERVANT!",
  "text": "The basest of men are they that yield no fruit on earth. Such men are verily counted as among the dead, nay better are the dead in the sight of God than those idle and worthless souls.",
  "teaser": "The basest of men are they...",
},
{
  "id": "Persian82",
  "title": "Persian 82",
  "section": "Persian",
  "number": "82",
  "exhort": "O MY SERVANT!",
  "text": "The best of men are they that earn a livelihood by their calling and spend upon themselves and upon their kindred for the love of God, the Lord of all worlds.",
  "teaser": "The best of men are they...",
},
{
  "id": "Postscript",
  "text": "The mystic and wondrous Bride, hidden ere this beneath the veiling of utterance, hath now, by the grace of God and His divine favor, been made manifest even as the resplendent light shed by the beauty of the Beloved. I bear witness, O friends! that the favor is complete, the argument fulfilled, the proof manifest and the evidence established. Let it now be seen what your endeavors in the path of detachment will reveal. In this wise hath the divine favor been fully vouchsafed unto you and unto them that are in heaven and on earth. All praise to God, the Lord of all Worlds.",
  "teaser": "The mystic and wondrous Bride...",
}]
export default hiddenWords